name: logstash
description: Logstash is a free and open server-side data processing pipeline that ingests data from a multitude of sources, transforms it, and then sends it to your favorite "stash."
annotations:
  title: Logstash
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
apiVersion: v2
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: vollgas/logstash
    url: https://www.vollgas.net/
    email: dev@vollgas.net
# dependencies:
#   - name: common
#     repository: file://../../../common
#     version: 1.0.7
home: https://www.elastic.co/logstash/
icon: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt280217a63b82a734/6202d3378b1f312528798412/elastic-logo.svg
sources:
  - https://www.elastic.co/
  - https://github.com/truenas/charts/tree/master/charts/elastic-search
  - https://www.elastic.co/guide/en/elasticsearch/reference/master/docker.html#docker-configuration-methods
keywords:
  - logs
  - logstash
